language: go

sudo: required

services:
  - docker

branches:
  only:
    - master

env:
  global:
    - secure: "W/QwzgEJAvj/OagGAxy6KvZOVr+RXmPGqb4NgFoqjYPgcjqo007OGKdNbVo70cnuLTYwyop1/lN8EXkvTmplisvgoWEFl8Tzj1jfAuDWW7h4PDW3d6aLSK2eimVvwdFNdpKKA7dMktc65G2kmD7BNh50dLYDH6iIf5K7iagOLfDArVj/bd9hTz0pi5gZH5OzSzmvfOetkoCAg74NtcObkjBrsT7diIhQVA/NBrAiZd5DkLVxeGE/FyYFLgfN6AnIiTdsSx7FlAwd/+Z15cnxnEA+sdCvRTOXJ7sk3d9SjTsSyMOeqe39GhXd2p9/XS4TjTMMGOd3Vlj+j47lv0gM6kbjC8S6lDVVQNq3j/absW0o9i4JzL7AqQSbvu8cMJYJoIuNi9lGRQ0SEhz6jWt0jxXmYZxWLedLMZJUcTj9luKd+RywnQnje5WOrTOrUA4aNfALBhmsPnDh7I4pbY5fPq3HxT22hgMPTwALUpq65A66d9EfSHZvoUbZ6OCChTOpveM65Csrwke5pCb03V/Kwws9i/N7qWcJeN60uH6l9W7amjC+9YCW+un+pduQpv8BQSewsDgdObbcWPzFqLVh2UJtpGrxTzqcsdBP7HhksolANmfi8zO3I4wgEpwk8azgrwLY08f1mVsBWsttqqyKufWCzoJR81PaSZVOM2xQ1p0="
    - secure: "jHzq/IZDZo3ZEfatxB1vnZLM8hFyJfiuehhN9ep3aKdAh7hginuT14wOM/Fnot0Gb7WHibdGoFi7khDh0Q43CAIfU3rEFlMGvLWiPhnKHyy8dbmdCFU1Y6vx9WZht+gXJKZzcsL3SfWB7q+ZbYLRWM/PebUqNIRwZg3bOBeLTHK3LzVg5e4STROJSiHqUwv/JMsmvP/mo/LGaQcxmLf00bwKBeuEGhpLp4NEi7y0G6jDAWpFlreMSwX5P4HkuZnzJWEr407aaArGPGX+CUm1f2fCQar5DbGyar5VqweY2HlHIcN1H8oVHwwbtsFjzpFgyPoilvxvs7uW0jhyzVxLhoLapXKa/YA3Edz9Yuw1hMSHOEWcPBzdHBrhbwZmhbS9qSX55WReXNuxPHoy7RrZE4np+tzz9gFxJFcmbWzlzJMQMBvosm5I7fhzydGsbrhY4ZXx0xzD91qbwa0QdWMZZMdg5aY7Yj5aNXZC4pTioxS4gHvhBUNMaNmec2jxlLdofzL0ckmR8aqvTY9eYyTLgKRPWv5HJPLY5XcO9SLAY5tMsnZLZqHa1rkrx4bd7IfGD7XVgUeB+HBg33zJR1Xx68HB2avvbNOYzNIOVNdJvv+8uSoZS7aMsOxWmpwfZ9bNqk2H27QzyDv5PlHKDutXSN1aSomAwjjPQISXk4DGHDA="

install:
  - go get github.com/constabulary/gb/...
  - sudo apt-get install -y make

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
  - make all

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=v1.0.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: qzwIN2VU9T7stmN/Jklwf9RagcBOoql6oWL1C5aBsUdUcaeel8lX76NvfYI3EDenK0IdYd9rO9GLiEYVAeBCYtafaD5o++Ybfpwki2gYv4DWxn8Wqv6wtGIP9OPLY3vmGMPxZQ+BZMzPdfYktz6EKkY0Vod++Rh7hrAHKbXs5C1kerMFyo5YO12EK42dOZtqUmiymwuY2X+dQIB3H3NtZ7AyeH/t/T5LAELHQXC8FYuyOjf4JwherxOrjxI6Trs14KrfdcAfXCYeLuUL/mthSL0s5qlOKIf7vHSOmko1WC6ggcH6dMKgXQGA52S9NxvFFSkZUCAtggntWNFc7vMyXtX59wVtcNtRsqrxPj5gUAwfQeU8R3MYBJ3AJQdI4u+9hDtNNyfN2mQWgBVdJS7/2b18fqgqyMyF/dGMVbu7OlRYqHpOTgKmbPJwuVorCO5wZl+z5XoYePsSWw8yFbUry2UHOOO9hYVm9bzihjdVf8WAUsV3hdMvCQ84kWWZ4WKmENWTe/Sf3ZFgKTBoaKTPuoYz6T2UV/dX5RPcAv7+eYzG0JpOHvvyjKGn5XDZk5TsLfgG/o60EmlULNci0s0GIUbrSbL6KcZoleWmYumiBTqOyBlu6XWQnmU4YCqTviGdGD0BhaLpAMCpGwIX5UnKkR9XuEdH0hcO204abKwS690=
  file: hashiconf.deployable.yml
  on:
    tags: false
    repo: timperrett/hashiconf-2016-demo
